stages:
  generate_data:
    cmd: python src/stages/data_generation.py
    deps:
    - src/data/data_generator.py
    - src/stages/data_generation.py
    params:
    - attrition_scenarios
    - company
    outs:
    - data/stages/raw/employees.csv
    - data/stages/raw/exit_interviews.csv
    - data/stages/raw/metadata.yaml
    - data/stages/raw/performance.csv
    - data/stages/raw/promotions.csv
    - data/stages/raw/recruitment_costs.csv
    - data/stages/raw/surveys.csv
    - data/stages/raw/training.csv
  preprocess:
    cmd: python src/stages/data_preprocessing.py
    deps:
    - data/stages/raw/employees.csv
    - src/stages/data_preprocessing.py
    params:
    - split
    outs:
    - data/stages/preprocessed/split_metadata.yaml
    - data/stages/preprocessed/test_data.csv
    - data/stages/preprocessed/train_data.csv
