# Company simulation parameters
company:
  name: "BFI Finance Indonesia"
  num_employees: 4000
  historical_years: 5
  random_seed: 42

# Attrition scenarios
attrition_scenarios:
  normal:
    rate: 0.50  # ~13% annual over 5 years
    description: "Normal market conditions"
    is_active: false
  low_stress:
    rate: 0.35  # ~8% annual over 5 years
    description: "Low competition, high retention period"
    is_active: true
  high_stress:
    rate: 0.65  # ~19% annual over 5 years
    description: "High competition or restructuring period"
    is_active: false

# Data splitting parameters
split:
  method: "hire_date" # status, hire_date
  train_end_date: "2023-12-31"
  test_start_date: "2024-01-01"

# Model configuration
model:
  type: "lightgbm_sklearn"
  n_estimators: 500
  num_leaves: 31
  learning_rate: 0.05
  feature_fraction: 0.9
  bagging_fraction: 0.8
  bagging_freq: 5
  class_weight: "balanced"
  max_depth: 7
  min_child_samples: 20
  reg_alpha: 0.1
  reg_lambda: 0.1
  boosting_type: "gbdt"
  objective: "binary"
  metric: "auc"
  n_jobs: -1

# Feature engineering parameters
features:
  categorical_encoding: "one-hot"
  standardize_numeric: true
  include_interaction_terms: false
  add_performance_categories: false

# MLflow tracking configuration for DagsHub
mlflow:
  dagshub_repo_name: "hr-attrition-analytics"
  dagshub_repo_owner: "saifulrijal873"